sudo: required

language: node_js

services:
  - docker

before_install:
  - docker pull chrislusf/seaweedfs
  - docker run -d -p 127.0.0.1:9333:9333 -p 127.0.0.1:8080:8080 chrislusf/seaweedfs server

before_script:
  - npm install -g gulp-cli

script:
  - gulp test